name: "Build, push, and deploy"

concurrency:
  group: manifest_diff_${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request: {}
  push:
    branches:
      - 'main'

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/amd64
          push: "${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
          tags: |
            datawiredev/prometheus-bigquery-exporter:${{ github.sha }}
          cache-from: |
            type=gha,scope=refs/heads/main
            type=gha,scope=prometheus-bigquery-exporter-${{github.ref}}
          cache-to: type=gha,mode=max,scope=prometheus-bigquery-exporter-${{github.ref}}
